/*
 * generated by Xtext
 */
package org.joclal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BrowserAutomationUiModule extends org.joclal.ui.AbstractBrowserAutomationUiModule {
	public BrowserAutomationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
