/*
 * generated by Xtext
 */
package org.joclal.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.joclal.ui.internal.BrowserAutomationActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BrowserAutomationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BrowserAutomationActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BrowserAutomationActivator.getInstance().getInjector(BrowserAutomationActivator.ORG_JOCLAL_BROWSERAUTOMATION);
	}
	
}
