/*
 * generated by Xtext
 */
package org.joclal.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractBrowserAutomationValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.joclal.browserAutomation.BrowserAutomationPackage.eINSTANCE);
		return result;
	}
}
