/**
 * generated by Xtext
 */
package org.joclal.validation;

import org.joclal.validation.AbstractBrowserAutomationValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BrowserAutomationValidator extends AbstractBrowserAutomationValidator {
}
