/**
 * generated by Xtext
 */
package org.joclal.ui.contentassist;

import org.joclal.ui.contentassist.AbstractBrowserAutomationProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class BrowserAutomationProposalProvider extends AbstractBrowserAutomationProposalProvider {
}
