/*
* generated by Xtext
*/
package org.joclal;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BrowserAutomationUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.joclal.ui.internal.BrowserAutomationActivator.getInstance().getInjector("org.joclal.BrowserAutomation");
	}
	
}
