/*
 * generated by Xtext
 */
package org.joclal;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BrowserAutomationRuntimeModule extends org.joclal.AbstractBrowserAutomationRuntimeModule {

}
